---
title: "HW11"
author: "Evan Howard"
date: "11/16/2021"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```


Problem 1 is associated with your personal dataset project. Submit your work for all problems in a single .pdf compiled with knitr. The Homework Data folder has a starting .Rmd template with spaces for you to fill in your answers to the questions. 

## Problem 1

This question is related to your personal data set project. The goal for the end of this week is to put together an initial visualization of your data and to perform one piece of analysis on your data.  

### (A) Use your dataset (possibly extended from what you originally submitted week 9) to create a visualization that summarizes an important property of the data. You should follow the principles of good visualization design that we discussed in week 4 and make sure to include a title, axis labels, and any other necessary components. 

### (B) Upload your figure to your github repository for the project and incorporate it into the readme file, along with a description (caption) of the plot that describes its contents. 

### (C) Choose one of the analytical techniques that we have discussed in class so far (either from the EDA section or the (un)supervised learning techniques) and apply it to your data. Explain in a brief paragraph why you chose this technique and what you learned about your data by performing this analysis (you don't have to upload this to github). This can be anything from a simple EDA technique like identifying outliers, making a box plot of a column, evaluating the summary statistics (Tukey's 5 numbers), to one of the regression models from supervised learning, or one of the clustering methods from unsupervised learning. This is not an exhaustive list of possibilities and as with the previous components doesn't need to be long or drawn out.

## Problem 2

In your own words, please write brief answers to the following: 

### (A) What is the curse of dimensionality?

### (B) What is the difference between MDS and PCA?

### (C) Give an example of a dataset for which dimension reduction would be a useful first step. 

### (D) What is a dendrogram and what type of clustering method is it used to represent?

### (E) What is the difference between supervised and unsupervised learning? 

## Problem 3

This problem checks your understanding of PCA and K means clustering. 

### (A)  Load the iris data as a dataframe. This is a classic dataset (originally published in 1936) that is frequently used as an initial set of test data. It consists of four numerical columns reporting the length and width of the sepal and petals of 150 iris plants and a final column reporting the specific subspecies. The version in the week 11 data folder also has an additional column with numerical column representing the subspecies. 

### (A) Make a scatterplot of petal width vs. petal length colored by the subspecies.

### (A) Use R to perform PCA  on the data with the four numerical columns as inputs and make a scatter plot of the top two principal components colored by subspecies.

### (A) What proportion of the variance is explained by these two components?

### (A) What are the loadings for each of the original numerical columns?

### (A) Apply K means clustering to the four numeric columns with three clusters. 

### (A) Apply K means clustering to the two principal components with three clusters. 

### (A) Which of the two K means clusterings is more accurate at predicting the subspecies correctly?

## Problem 4 
Use the following exploratory data analysis projects about candy preferences:   https://fivethirtyeight.com/videos/the-ultimate-halloween-candy-power-ranking/   to provide brief responses to the following: 
 
### (A) What research questions are the articles trying to answer? Where does your favorite candy rank in their list?

### (B) Can you tell where the underlying data came from? 

### (C) What are some other ways you could use to determine which candy  is best?

### (D) What type of regression is used in the candy power ranking article? How does the interpretation of the coefficients match up with what we discussed in class?

### (E) What do you think about the visualizations and examples in these pieces?

